# # # # # # # # # # # # # # # 


Deny_message: |-
  &b&l[ &f&lServer &b&l] &c명령어 %cmd%(은)는 서버 보안상 사용이 금지 되어있습니다.
reloaded: |-
  &b&l[ &f&lServer &b&l] &a성공적으로 설정을 재로드 하였습니다.

send_deny_msg: true
Stacktrace_On_File_Exception: false

#모두 소문자로 ("" 사이에 명령어 입력)
Exploit-CMDs:
- "//calc"
- "//calculate"
- "//eval"
- "//evaluate"
- "//solve"
- "/hd readtext"
- "/holo readtext"
- "/hologram readtext"
- "/holograms readtext"
- "/holographicdisplays readtext"
- "/pex promote"
- "/pex demote"
- "/promote"
- "/demote"
- "/execute"
- "/permissionsex promote"
- "/permissionsex demote"
- "/prom"
- "/rankup"
- "/dem"
- "/rankdown"